import { Inter } from "next/font/google";
import styles from "./globals.module.css"; // CSSモジュールのインポート
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Team OPS Login Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}